### ISSUE TITLE
Cannot import McuOpenPnP_Machine/Projects/tinyk20_OpenPnP_AutoFeeder/

### ISSUE THREAD

**Issue by duncanellison** [ErichStyger/McuOpenPnP_Machine#1]
I'm trying to import the AutoFeeder project into KDS 3.2.0, but can't get a clean build.

What dependencies also need to be created to build this?

**Comment by ErichStyger** [comment]
Have you downloaded and installed the McuOnEclipse Processor Expert components from https://sourceforge.net/projects/mcuoneclipse/?
See https://mcuoneclipse.com/2014/10/21/mcuoneclipse-releases-on-sourceforge/

**Comment by duncanellison** [comment]
Yes, I installed the two beans packages and saw that the components were now available in the Eclipse PE section.  Latest seem to be 31-12-19, so that's what I used.

Then did an 'import'  of the project from the files in this repo, then did a Generate PE code, then a build.

I seem to be missing CPU.h and PE_Types.h

I assume that I don't need to do anything specific about FreeRTOS ?

**Comment by duncanellison** [comment]
![Capture](https://user-images.githubusercontent.com/1681591/76707465-49cef580-66e7-11ea-8011-9ce51175f003.JPG)

**Comment by ErichStyger** [comment]
The missing CPU.h and PE_Types.h indicates to me that code has not been generated? Do you have  folder Generated_Code with these files in it?

**Comment by ErichStyger** [comment]
I see that third error (Generator Error): so your code generation was not sucessful. Did you load that project before you had installed the packages?

**Comment by ErichStyger** [comment]
This is how it should look like:
![grafik](https://user-images.githubusercontent.com/3187954/76708688-1dbc7000-66f9-11ea-836a-63d034e1c12b.png)
![grafik](https://user-images.githubusercontent.com/3187954/76708694-2ca32280-66f9-11ea-9a31-1b04aa7ff106.png)

**Comment by duncanellison** [comment]
Hi Erich,  I loaded the PE components first, then imported the project, then tried to generate code and that was the result.  I just tried to generate the PE code again and now I have a (slightly) different result.  CPu.c is there, but not the header file :-(  and I'm looking at 2,222 errors now, mainly bad declaration errors.  I'll post a screenshot.   p.s. thanks for helping with this.

**Comment by duncanellison** [comment]
![image](https://user-images.githubusercontent.com/1681591/76708768-5b1cff80-66f1-11ea-9fdd-ca554504eb5f.png)

**Comment by duncanellison** [comment]
![image](https://user-images.githubusercontent.com/1681591/76708779-76880a80-66f1-11ea-91c3-1b2b2dda4254.png)

**Comment by duncanellison** [comment]
![image](https://user-images.githubusercontent.com/1681591/76708884-5442bc80-66f2-11ea-8db4-3c53a26ac719.png)

**Comment by ErichStyger** [comment]
Can you attach your .pe file (in the project root folder) so I can have a look?

**Comment by duncanellison** [comment]
Here you go ... 
[ProcessorExpert.pe.txt](https://github.com/ErichStyger/McuOpenPnP_Machine/files/4334946/ProcessorExpert.pe.txt)

**Comment by ErichStyger** [comment]
thanks. That file works fine for me. Not sure what I'm missing, or if I have a change on my side which is not present on your end. Have you already restarted the IDE?

**Comment by duncanellison** [comment]
Yes, I tried restarting the IDE , then a build - same result.  Tried regenerating  the PE code - no warnings, but still won't build.

I'm getting a ton of this stuff in the console 

 
![image](https://user-images.githubusercontent.com/1681591/76709631-2791a380-66f8-11ea-9884-07a96351ddaa.png)

It must be something fairly trivial I'm missing in my build environment?

**Comment by ErichStyger** [comment]
it looks like it did not properly generate all the needed files. Strange. And you are using KDS 3.2.0, correct?

**Comment by duncanellison** [comment]
Correct KDS 3.2.0 direct from from the NXP site. 

If it helps, here's an archive of the project
[non-working.zip](https://github.com/ErichStyger/McuOpenPnP_Machine/files/4334991/non-working.zip)

**Comment by ErichStyger** [comment]
Here is what I have (with generated files) on my machine:
[tinyk20_OpenPnP_AutoFeeder.zip.txt](https://github.com/ErichStyger/McuOpenPnP_Machine/files/4334992/tinyk20_OpenPnP_AutoFeeder.zip.txt)

**Comment by duncanellison** [comment]
OK, Thanks - let me try importing that

**Comment by ErichStyger** [comment]
I believe it is about a fix I have made in the components. I get the errors if I compile your files. But it works fine if I regenerate the code. Give me a bit of time to generate the components package for you.

**Comment by duncanellison** [comment]
OK, that DOES build (withing the same IDE environment) and gives me an .elf file.  Hmmm ...  now I'm left wondering what was missing before.

BTW (caution - thread drift) - I see there is activity on this project and you dropped an .srec file onto the repo.  How are you converting the .elf to .srec?
 

Edit : I see now there is an .srec file generated too.  Must be a config option.

**Comment by ErichStyger** [comment]
Can you try with the attached components?
[Components_15.03.2020.zip.txt](https://github.com/ErichStyger/McuOpenPnP_Machine/files/4335009/Components_15.03.2020.zip.txt)

**Comment by ErichStyger** [comment]
Note: I checked the differences in the generated files, but there was nothing really hitting my eye. What is strange that your generated code somehow does not know about the standard types like int8_t or int32_t somehow. Strange.

**Comment by ErichStyger** [comment]
.srec: it is an option in the 'Toolchains' tab, see https://mcuoneclipse.com/2014/04/11/gnu-additional-tools-create-flash-image-print-size-and-extended-listing-options/

**Comment by duncanellison** [comment]
re : Srec - great that's handy for J-Flash Lite

**Comment by duncanellison** [comment]
Update : with the updated PE components, same result - doesn't build.

With the generated code you sent, I can compile, build and debug 100%.  Made changes to the code and they were reflected in the object sent to the uC.  

Got to rush off now, but I'll investigate a little further tomorrow what the differences might be.  Clearly the build environment is OK since it can compile and build your code version properly, so it must be in the PC components somehow.  

Thanks for you help on this - worst case, I can use your build to debug an issue I'm having with the motor drive which requires me to add some debug code.

**Comment by ErichStyger** [comment]
ok, so this means it is not about the components. I noticed that the Processor Expert (core) for you generated slightly different things (comment headers). Could you check what you have installed? Below is what I have:
![grafik](https://user-images.githubusercontent.com/3187954/76732719-a241d980-675f-11ea-94ea-4c8d7533907d.png)

**Comment by duncanellison** [comment]
I have just the same  ...

**Comment by duncanellison** [comment]
![image](https://user-images.githubusercontent.com/1681591/76771612-80644900-6797-11ea-9831-f4a85fc8df52.png)

**Comment by duncanellison** [comment]
![image](https://user-images.githubusercontent.com/1681591/76771673-9eca4480-6797-11ea-8e14-d35f807eba5c.png)

**Comment by duncanellison** [comment]
I'm happy to report no issues at all with the project pack you sent me above within the same environment - odd.

**Comment by ErichStyger** [comment]
yes, this is odd. I'm going to close the issue, simply re-open if you think it is appropriate.

**Comment by CircuitSetup** [comment]
FWIW, I just loaded everything up and it built without issue.

**Comment by duncanellison** [comment]
Hi Erich,  

I can confirm that if I load the project from the file you gave above, plus the updated components, I can do a clean compile right out of the gate as others are reporting.  

However ...  If I run Project > Generate Processor Expert Code then try to build, it breaks, throwing out all the undefined types errors we discussed earlier.

Tried deleting the Generated_Code and Static_code folders to let them re-generate completely, then tried again, but this time I get a different failure mode with .h files missing 

C:/Users/Duncan Ellison/kds_workspace.kds/tinyk20_OpenPnP_AutoFeeder/Generated_Code/BitIoLdd5.h:91:22: fatal error: GPIO_PDD.h: No such file or directory

C:/Users/Duncan Ellison/kds_workspace.kds/tinyk20_OpenPnP_AutoFeeder/Generated_Code/BitIoLdd1.h:94:22: fatal error: GPIO_PDD.h: No such file or directory

C:/Users/Duncan Ellison/kds_workspace.kds/tinyk20_OpenPnP_AutoFeeder/Generated_Code/BitIoLdd1.h:94:22: fatal error: GPIO_PDD.h: No such file or directory

I guess others are just aiming to get a build and create the .src / .hex and be done, but I'm trying to add some additional fault checking code to make assembly and maintenance easier (e.g. run 90 steps and check each hole is clear)  

I can manage since I can compile the code if I don't mess with the components, but its frustrating no knowing what's causing this.  Like I said I'm a newbie at Processor Expert, but I think this is the way it should work and keen to be able to add to this project.

Duncan

**Comment by duncanellison** [comment]
p.s.  The Master project is the other way round.  It doesn't build unless I DO re-generate the PE, then it builds fine, this leads me to think that my build environment is fine and the components.

**Comment by ErichStyger** [comment]
The GPIO_PDD.h is iniside Static_Code/PDD and is only generated at project creation time, not at build or code generation time. If it does not find it on your machine, it means that it has been deleted? Strange.
As for the masters project: after importing it from git, you have to generate code (either manually or automatically) because the generated code is not part of the Git repo, because usually generated code shall not be on a source repository.

I think I will now put the generated code on git too: that way there is always a working version and there is no need to generate code.
