### ISSUE TITLE
Tape motor not moving with OpenPnp M850

### ISSUE THREAD

**Issue by CircuitSetup** [ErichStyger/McuOpenPnP_Machine#2]
The tape motor appears to work like it should with the on-board buttons, but does not move with an M850 command from OpenPnp. 

I see in the code where MOT_Speed is used for the buttons to control the tape motor, but am not seeing the same function where M850 is handled in comm.c (or m851). It doesnt matter if the tape cover switch is depressed or not. Maybe I'm missing something?

**Comment by ErichStyger** [comment]
I'm a bit in crunch right now, but I will look into this in the next days.

**Comment by duncanellison** [comment]
Erich, just to advise that I'm seeing the exact same issue too.  Pushing the buttons works 100% as expected, so there's no hardware issues here.

I kind of expected the tape motor code to be on a separate free running thread taking care of itself, but I don't see anything like that in the code.

Your assistance would be much appreciated.

**Comment by ErichStyger** [comment]
ok, thanks for confirming. I don't have the hardware with me because of Corona and the university closure. I have to see if I can access the hardware and try it out on my side, but it will take me until the weekend to get there.

**Comment by duncanellison** [comment]
Hi Erich,  we are most grateful to you for your help.   We don't mind poking around in the code and trying to debug physically this if you could give us some steerage on where to look.  I don't think either of us are FreeRTOS experts, but we might even learn something :-)

We both have pretty identical hardware and can try out any changes.  Our biggest challenge is that we can't find the code that's supposed to work the tape feeder under serial command.

BTW, I can confirm that it's not specifically an 'M850' problem as I'm sending the raw serial command to mine with the same result.

It feels like we are both missing something really obvious.

**Comment by ErichStyger** [comment]
The M850 command is received by the Master board (a tinyK22 (K22FN512), you can see it inhttps://mcuoneclipse.files.wordpress.com/2018/06/tinyk22.png?w=584&h=493) and handled in https://github.com/ErichStyger/McuOpenPnP_Machine/blob/master/Projects/tinyK22_OpenPnP_Master/Sources/Feeder.c
same for the M851 command.

` 
} else if (UTIL1_strncmp((char*)cmd, "M850 ", sizeof("M850 ")-1)==0) { /* feed operation: "M850 <addr> <n> mm  */
    *handled = TRUE;

    p = cmd + sizeof("M850 ")-1;
    res = UTIL1_xatoi(&p, &addr);
    if (res==ERR_OK) {
      res = UTIL1_xatoi(&p, &mm);
      if (res==ERR_OK) {
        UTIL1_strcpy(buf, sizeof(buf), "CMD ");
        UTIL1_strcatNum32s(buf, sizeof(buf), addr);
        UTIL1_strcat(buf, sizeof(buf), " FWD ");
        UTIL1_strcatNum32s(buf, sizeof(buf), mm);
        UTIL1_strcat(buf, sizeof(buf), " mm");
        return FEED_SendCommand(buf, io);
      }
    }
  } else if (UTIL1_strncmp((char*)cmd, "M851 ", sizeof("M851 ")-1)==0) { /* post-pick operation: "M851 <addr> <n> mm  */
    *handled = TRUE;
    /* We are not doing anything right now. Print 'ok' message so it can be parsed by OpenPnP Regular Expression */
    CLS1_SendStr("ok\r\nok\r\nok\r\n", io->stdOut);
  }
`
So the OpenPnP M850 command gets translated into a CMD x FW command to the feeder. This command is supported by the feeder:

`--------------------------------------------------------------
TinyK20 OpenPnP Feeder
--------------------------------------------------------------
CLS1                      ; Group of CLS1 commands
  help|status             ; Print help or status information
KIN1                      ; Group of KIN1 commands
  reset                   ; Performs a software reset
  help|status             ; Print help or status information
CMD                       ; Group of CMD commands
  help|status             ; Print help or status information
  0 FWD <n> mm            ; Move feeder <n> mm forward (multiple of 2)
  0 REV <n> mm            ; Move feeder <n> mm backward (multiple of 2)
  0 CNT                   ; Count number of feeders
`

I hope that makes sense now?

**Comment by CircuitSetup** [comment]
Thanks @ErichStyger. Right, that makes sense. 

@duncanellison actually added some code to encoder.c to handle the tape pull motor that seems to have fixed the issue. It's similar that what is in Application.c for the FWD button.
