### ISSUE TITLE
Lasercutter files

### ISSUE THREAD

**Issue by a2luca** [ErichStyger/McuOpenPnP_Machine#3]
Hello,
first I want to thank you for sharing your project with the OpenSource community. But I was wondering if you may want to share your Lasercut files like in the following blog post (https://mcuoneclipse.com/2018/06/26/building-a-diy-smt-pickplace-machine-with-openpnp/).
Thank your already for answering this "Issue"

**Comment by ErichStyger** [comment]
they are inside the 'Inkscape' folder of this repository.
